# -*- coding: utf-8 -*-
"""WebScrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EMlPu_1PBA__-WSh_isYoWV2BEooPEmM

Python has **‘uszipcode’ **package that provides city and state names among other geographical details of all the cities in the country.
"""

!pip install uszipcode

!pip install --upgrade uszipcode

import pandas as pd
from collections import defaultdict
from uszipcode import SearchEngine, SimpleZipcode, ComprehensiveZipcode


# Getting basic geographical data such as zipcode, state, city
search = SearchEngine(simple_zipcode=True);

# search by a 'big' population and return all cities
results   = search.by_population(0 ,10000000, returns = 100000)

# keeping only relevant information
geo_data  = defaultdict(list)
for r in results:
    geo_data['City'].append(r.city)
    geo_data['State'].append(r.state)
df = pd.DataFrame(geo_data)

# dropping duplicate values as a city has multiple zip codes
df = df[~df.City.duplicated()]
df.reset_index(inplace = True, drop = True)

# creating base URLs from city and state names
def city_url(x):
    url = 'https://www.apartments.com/' + x.City.lower() + '-' + x.State.lower()
    return url

  # for all cities
df['URL'] = df.apply(city_url, axis=1)

# saving
df.to_csv('url_data.csv', index = False)